### ISSUE TITLE
Crashes when launched on lunar client

### ISSUE THREAD

**Issue by EthGaming1** [RaphiMC/ImmediatelyFast#245] opened 2024-07-05 14:02 UTC
so i was just launching lunar client version 1.20.4 with mods like sodium, indium, iris and ferritecore and all that and the game just crashed for no reason, i realy dont know why it crashed

**Comment by RaphiMC** [comment] 2024-07-05 14:03
Duplicate of #223

**Closed as completed by RaphiMC** 2024-07-05 14:03 UTC
Labels: duplicate
