### ISSUE TITLE
Conflicting mixins with Porting-Lib causes game crash

### ISSUE THREAD

**Issue by spaghettube** [RaphiMC/ImmediatelyFast#11] opened 2022-12-27 03:34 UTC
Mixin Conflict Helper, by isXander warned me of an issue between your mod and https://github.com/Fabricators-of-Create/Porting-Lib .
Here's the log: 
[2022-12-27-3.log](https://github.com/RaphiMC/ImmediatelyFast/files/10305698/2022-12-27-3.log)

**Comment by RaphiMC** [comment] 2022-12-27 10:32
I looked into the mixins conflict and I would say the other mod should fix it. They are using a large part of the local variable table inside a huge method. Basically any modification to that method will break the Porting-Lib mod. I will try to come up with a workaround, but its unlikely that I can fix the issue, based on Porting-Lib assumption that the local variable table isn't being modified by some other mods. I opened an issue on their issue tracker.

Linked issue: https://github.com/Fabricators-of-Create/Porting-Lib/issues/25

**Comment by StarskyXIII** [comment] 2022-12-27 10:54
Please try to remove your MemoryLeakFix mod

**Comment by StarskyXIII** [comment] 2022-12-27 11:01
If you have Porting Lib(Create), MemoryLeakFix and ImmediatelyFast at the same time, game will crash when startup.
When I remove MemoryLeakFix mod, I can join the game normally.

**Comment by RaphiMC** [comment] 2022-12-27 11:02
This isn't caused by MemoryLeakFix. I could reproduce it locally with just the two mods

**Comment by StarskyXIII** [comment] 2022-12-27 11:05
Yeah, I know, but I have no idea why game crash on startup with MemoryLeakFix.
But when I remove it, game will not crash on startup

**Comment by RaphiMC** [comment] 2022-12-27 11:05
The game crashes as soon as you look at a map. Maybe MemoryLeakFix does something weird which causes the map rendering code to be loaded earlier

**Comment by SplendidAlakey** [comment] 2022-12-27 11:06
Because MemoryLeakFix forceloads all mixins on startup.

**Comment by RaphiMC** [comment] 2022-12-27 11:10
Here is a build of ImmediatelyFast which fixes the crash error on my side. You can use that until the issue gets fixed in Porting-Lib:
[ImmediatelyFast-1.1.1.jar.zip](https://github.com/RaphiMC/ImmediatelyFast/files/10307741/ImmediatelyFast-1.1.1.jar.zip)

**Comment by RaphiMC** [comment] 2022-12-29 00:22
I have made a workaround on my end now because the devs of Porting-Lib seem to be inactive. Should be fixed in the next release.

**Closed by RaphiMC** 2022-12-29 00:22 UTC
