### ISSUE TITLE
Not compatible with Feather client

### ISSUE THREAD

**Issue by ghost** [RaphiMC/ImmediatelyFast#83] opened 2023-07-07 15:42 UTC
[crash-2023-07-07_18.33.32-client.txt](https://github.com/RaphiMC/ImmediatelyFast/files/11983747/crash-2023-07-07_18.33.32-client.txt)

I only had feather client, fabric api and this mod enabled, got this error

**Comment by RaphiMC** [comment] 2023-07-07 15:43
Duplicate of #75

**Closed as completed by RaphiMC** 2023-07-07 15:43 UTC
Labels: invalid
