### ISSUE TITLE
[1.20.1 NeoForge] Invisible items for 3D rendered blocks in inventory when carrying Ars Nouveau spellbook

### ISSUE THREAD

**Issue by Cragsand** [RaphiMC/ImmediatelyFast#225] opened 2024-06-02 13:39 UTC
Older version 
- Description: 3D item blocks are completely invisible when holding Ars Nouveau spellbook
- Version: ImmediatelyFast-Forge-1.2.13+1.20.4.jar: 
- Full Log: https://gist.github.com/Cragsand/0c3b08f279dcd620809ef211b49aeecd

Latest version 
- 3D items are transparent when holding Ars Neouveau spellbook
- Version: ImmediatelyFast-Forge-1.2.17+1.20.4.jar
- Full Log: https://gist.github.com/Cragsand/e6b7921400fcc1eb37e5c337fe6046ac

Troubleshooting:
- Disabling ImmediatelyFast shows block again as usually.
- Conflicting mod: https://modrinth.com/mod/ars-nouveau

Newer version - Transparent - Animated gif example (Press the play button on top right)
![GIF 2024-06-02 15-33-04](https://github.com/RaphiMC/ImmediatelyFast/assets/49168045/aedbcd1b-0303-48bf-b194-312457101099)

Older version - Completely invisible - Animated gif example (Press the play button on top right)
![GIF 2024-06-02 15-24-35](https://github.com/RaphiMC/ImmediatelyFast/assets/49168045/e26a0a12-bb04-431a-bf88-d32f6d63468d)

EDIT: 
Related issues:
- https://github.com/embeddedt/embeddium/issues/75
- https://github.com/Sonmok14/FromTheShadows/issues/14
- https://github.com/embeddedt/embeddium/issues/272

**Comment by RaphiMC** [comment] 2024-06-02 13:41
Duplicate of #133

**Closed as completed by RaphiMC** 2024-06-02 13:41 UTC
Labels: duplicate
