### ISSUE TITLE
AppleSkin exhaustion underlay appears in front of hunger bar

### ISSUE THREAD

**Issue by KianKhadempour** [RaphiMC/ImmediatelyFast#38] opened 2023-02-12 21:00 UTC
If I have ImmediatelyFast-1.1.8+1.19.3 loaded with appleskin-fabric-mc1.19.3-2.4.2 (and fabric-api-0.73.2+1.19.3) the exhaustion underlay appears in front of the hunger bar instead of behind it:

![image](https://user-images.githubusercontent.com/43736613/218336559-f640e0e2-9572-4f7b-85f0-bbcd9270a8d1.png)

If I turn off ImmediatelyFast, it goes back to normal. This seems to be the same issue as [this reddit post](https://www.reddit.com/r/feedthebeast/comments/10w28s2/1192_fabric_appleskins_exhaustion_meter_appears/). If you need any logs or something else from me, I can provide them.

**Comment by RaphiMC** [comment] 2023-02-17 10:26
Maybe related to #22

**Comment by ghost** [comment] 2023-04-26 13:16
<p>I have exactly the same problem in MC 1.19.4 to. I saw this bug for sure with a minimal amount of mods:</p>

<ul>
<li>Fabric API: 0.79.0</li>
<li>Apple Skin: 2.3.4</li>
<li>Immediately Fast: 1.1.12</li>
</ul>

<p>I also didn't attach any logs as there are no errors or warnings in the logs when reproducing this bug.</p>

![2023-04-26_16 04 21](https://user-images.githubusercontent.com/126811494/234584814-85f74bb2-89e1-4eea-8c46-39a1f4114b29.png)

![2023-04-26_16 05 46](https://user-images.githubusercontent.com/126811494/234584820-cb0cd690-a7ff-44d9-817f-4a8a846c3114.png)

**Comment by RaphiMC** [comment] 2023-04-26 14:14
How is it supposed to look? Can you post that here for reference

**Comment by Gaming32** [comment] 2023-04-26 15:17
The first picture is how it's supposed to look.

**Comment by RaphiMC** [comment] 2023-04-29 11:19
The issue should be fixed. Someone please verify before I close it: https://upload.raphimc.net/file/K79pUE69C39gtbJI/0zU93mVaNIWh48GR/ImmediatelyFast-1.1.13%2B1.19.4.jar

**Comment by KianKhadempour** [comment] 2023-05-01 00:36
It is fixed in 1.19.4 but is there any way you can fix it in the other versions as well? I would but I have barely any experience with Java.

**Comment by RaphiMC** [comment] 2023-05-01 09:51
Probably not, as I don't want to maintain 5 different versions of the same mod. Only 1.19.4 and 1.20 have this fix currently

**Closed as completed by RaphiMC** 2023-05-01 09:51 UTC
Labels: bug, confirmed, external-mod

**Comment by ghost** [comment] 2023-05-29 11:24
> The issue should be fixed. Someone please verify before I close it: https://upload.raphimc.net/file/K79pUE69C39gtbJI/0zU93mVaNIWh48GR/ImmediatelyFast-1.1.13%2B1.19.4.jar

Can you upload this version again or just release on GitHub/Modrinth? I can't download this version anymore.

**Comment by RaphiMC** [comment] 2023-05-29 11:26
The modrinth release will come when 1.20 releases. Here is the 1.19.4 version again: https://upload.raphimc.net/file/FqhC0ojaHNRZvCh2/gY3xmkzzdE4MiYmo/ImmediatelyFast-1.1.13%2B1.19.4.jar

**Comment by ghost** [comment] 2023-05-29 11:39
> The modrinth release will come when 1.20 releases. Here is the 1.19.4 version again: https://upload.raphimc.net/file/FqhC0ojaHNRZvCh2/gY3xmkzzdE4MiYmo/ImmediatelyFast-1.1.13%2B1.19.4.jar

Thanks!

**Comment by Abalieno** [comment] 2023-07-14 09:37
> Probably not, as I don't want to maintain 5 different versions of the same mod. Only 1.19.4 and 1.20 have this fix currently

Why going against the community like that? There was a general agreement between mod and modpack developers to adopt 1.19.2 and skip the later versions, to then make the jump to 1.20.

No one uses 1.19.4. Most mods weren't ported, it misses AE2, kubejs, quest support and tons of others. And instead you're cutting support for 1.19.2 that is the only version used extensively in modpacks right now.

**Comment by RaphiMC** [comment] 2023-07-14 09:49
ImmediatelyFast was always designed to be a latest minecraft version only mod like other optimization mods do as well (Sodium, Enhanced Block Entites, ...). Its a lot more work to support multiple old minecraft versions as the codebase differs more and more with every minecraft update and keeping the same featureset becomes gradually more work intensive because I have to essentially rewrite it for every major minecraft version. I am making this mod in my freetime besides multiple other FOSS projects and just don't have the time to worry about maintaining the mod for old minecraft versions.
As a solution you can just delete ImmediatelyFast or disable the hud_batching optimization in the config.

**Comment by Abalieno** [comment] 2023-07-14 14:34
That's THE reason why coordination between mod developers is necessary to not keep splintering the community.

Agreeing on a version to develop on is helpful to avoid having to support multiple versions. To avoid doing more pointless work. If you want to version chase, it's fine. But at least keep ONE other version that people can actually use, at least for bug fixes.

That version is currently 19.2, not 4. No one is using .4 on any modpack because they either already jumped on 1.20, or use a supported version like 19.2.

And I already read that kubejs is skipping 1.20/1.20.1 because mojang is making bigger breaking changes in 20.2 soon.

The more things keep breaking on mojang side, the more the community needs to organize better. If 1.20.2 drops and there's an effort to go there, there's no reason anymore to keep supporting 20 and 20.1, no one is going to stay there. Same as it was pointless to go to 19.3/4 with breaking changes when 1.20 was already imminent.

I guess your reason to do 19.4 rather than 19.2 was that it's probably much closer to 1.20, code-wise.

**Comment by Felix14-v2** [comment] 2023-07-15 22:42
@Abalieno you hate 1.19.4 just because... some modders don't support it...? Seriously? 1.19.3-1.19.4 has **a ton** of new optimisations, and for me ≤1.19.2 is literally unplayable compared to 1.19.4. You should ask devs to support modern versions instead of buggy and unoptimised ones.

**Comment by Abalieno** [comment] 2023-07-16 12:46
There isn't a single rational reason to play on 19.4.

"some modders" means you have no recipe support, no quests, already cutting out any sensible modpack. All big mods are staying on 19.2 Botania, AE2, Create, MI. Same for everything on Forge side. I really wonder what are you playing on 19.4 if not just vanilla.

Vanilla optimizations are a minuscule bump compared to the work of modders, and as far as I know there was a slight boost on 1.20 (copied from mods), not 19.4.

And there's again no reason to use 19.4 when 1.20 is available. There is better mod support on 1.20 already NOW, compared to 19.4. You want that mysterious performance? Play on 1.20.

And it's not an opinion. Look even at # mod download on curseforge between versions. Most players continue to be on 19.2, because that's the "current" version, waiting for 1.20 to shape up. 19.4 is dead.

I didn't ask to drop support for 1.20. Only for 19.4 that was never adopted for a bunch of practical reasons, and while 1.20 exists.

![ukil78l](https://github.com/RaphiMC/ImmediatelyFast/assets/4656436/9f86a117-4de5-4f7e-8c36-d4b68afe20d6)

Just an example from a mod that bothered being on all versions.

**Comment by Abalieno** [comment] 2023-07-16 18:40
Some better data to make the point. Courtesy of Shedaniel

![werwerew](https://github.com/RaphiMC/ImmediatelyFast/assets/4656436/483c2c9e-d18c-4ae8-af9b-63a7247cb8b8)

**Comment by RaphiMC** [comment] 2023-08-06 18:40
I finally backported the 1.19.4 features of IF to the 1.19.2 version. Just letting you know in case you are still interested

**Comment by Abalieno** [comment] 2023-08-08 12:45
Yes, I already noticed. And thank you :)
