### ISSUE TITLE
[1.20.1] 3D Models (Items and blocks) in Hotbar are Dark Gray/Transparent

### ISSUE THREAD

**Issue by Ninjawolf0007** [RaphiMC/ImmediatelyFast#192] opened 2024-04-14 01:36 UTC
Game Version:
Minecraft version 1.20.1

Mods:
Forge version 47.2.23
ImmediatelyFast version 1.2.11
Ars Nouveau version 4.9.0
Curios API 5.8.0-beta.2

All 3D model items and blocks in the hot bar turns transparent while an Ars Nouveau spell book is in the hot bar (see below). This appears to be an interaction between the two mods, but I can't figure out what exactly is causing it. If ImmediatelyFast is disabled, this problem goes away.

![2024-04-13_18 11 42](https://github.com/RaphiMC/ImmediatelyFast/assets/11599572/e417ba7e-bc1b-4f5b-a710-f80da7217d3a)
![2024-04-13_18 11 53](https://github.com/RaphiMC/ImmediatelyFast/assets/11599572/1e0cfe96-199f-43af-9f75-12f8e64b6492)

**Comment by RaphiMC** [comment] 2024-04-14 08:21
Duplicate of #133

**Closed as completed by RaphiMC** 2024-04-14 08:21 UTC
Labels: duplicate
