### ISSUE TITLE
Items in hotbar render over F3 debug graphs while using ImmediatelyFast

### ISSUE THREAD

**Issue by mrjasonn** [RaphiMC/ImmediatelyFast#177] opened 2024-02-16 13:21 UTC
Without ImmediatelyFast:
![2024-02-16_21 13 58](https://github.com/RaphiMC/ImmediatelyFast/assets/120269221/216f5388-7d18-48bd-bc06-28f3cff4b55d)
With ImmediatelyFast (please ignore broken debug chart that was one time bug):
![2024-02-16_21 15 45](https://github.com/RaphiMC/ImmediatelyFast/assets/120269221/ae336ba7-d9a5-4375-8511-bde423f60def)
This is also the same case when using without any other mods except the Fabric Loader which is necessary and also I think it's important to not obstruct F3 debug graphs as people could actually need to see the whole of them in some environments where they cannot remove items from hotbar

<details>
<summary>Mod list</summary>
	- boostedbrightness 2.2.0
	- fabric-api 0.96.1+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.13+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.1+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.1+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.0+44c0f8c64f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.23+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.7+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.63+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.11+06274a474f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.18+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.0+d74054c14f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.18+b66dcf784f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.10+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabricloader 0.15.5
	   \-- mixinextras 0.3.2
	- immediatelyfast 1.2.10+1.20.4
	   \-- net_lenni0451_reflect 1.3.2
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- lithium 0.12.1
	- minecraft 1.20.4
	- reeses-sodium-options 1.7.2+mc1.20.4-build.102
	- sodium 0.5.8+mc1.20.4
	- sodium-extra 0.5.4+mc1.20.4-build.116
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sspb 3.2.1
	- wi_zoom 1.5-MC1.20.4
</details>

**Comment by RaphiMC** [comment] 2024-02-16 13:25
Try it without any other mods

**Comment by mrjasonn** [comment] 2024-02-16 13:25
> Try it without any other mods

Will do please wait ~3-5 mins

**Comment by RaphiMC** [comment] 2024-02-16 13:27
Might be a duplicate of #65

**Comment by mrjasonn** [comment] 2024-02-16 13:30
> Try it without any other mods

Ok it is still like that with only Fabric Loader and ImmediatelyFast (except pie chart I guess just bugged when I took the with ImmediatelyFast screenshot and tested now with the other mods the debug chart still shows so just that is one time bug)

**Comment by RaphiMC** [comment] 2024-02-16 13:34
So I will leave the issue open, but don't expect a fix anytime soon since the issue isn't really severe and fixing it would require larger code changes which might reduce mod compatibility (Especially considering that there are mods which replace the F3 HUD)

**Comment by mrjasonn** [comment] 2024-02-16 13:35
> So I will leave the issue open, but don't expect a fix anytime soon since the issue isn't really severe and fixing it would require larger code changes which might reduce mod compatibility (Especially considering that there are mods which replace the F3 HUD)

But wouldn't it be easy to just have the graphs render over that?

**Comment by RaphiMC** [comment] 2024-02-16 13:37
Thats what they are supposed to do, but I guess something breaks when IF optimizes the way they are rendered

**Comment by mrjasonn** [comment] 2024-02-16 13:37
> Might be a duplicate of #65

Yes, it's partially a duplicate of #65, but depends on where you'd like to track this.

**Comment by RaphiMC** [comment] 2024-02-16 13:38
I am gonna leave this issue open since the other one is already closed

**Comment by RaphiMC** [comment] 2024-02-16 13:52
This seems to be fixed in the 1.20.5 version of ImmediatelyFast, so it was probably some broken Minecraft code to begin with as the 1.20.4 and 1.20.5 version of ImmediatelyFast have the same optimizations. I am not going to fix this issue in <=1.20.4 versions of ImmediatelyFast as its not worth the time

**Closed as completed by RaphiMC** 2024-02-16 13:52 UTC
Labels: bug, confirmed
