### ISSUE TITLE
Frame rate issues with latest version of ImmediatelyFast on the MCC Island server.

### ISSUE THREAD

**Issue by BlizzLee** [RaphiMC/ImmediatelyFast#57] opened 2023-04-12 19:28 UTC
Hello, I have the Fabulously Optimized mod pack installed (mod pack version 4.7.1), and I just recently updated ImmediatelyFast to the latest version through Check for Updates in Curseforge. After installing the latest version of your mod, I went onto the MCC Island server and I immediately started having frame rate issues. So I uninstalled the mod pack and reinstalled it to revert the latest update of ImmediatelyFast, and I no longer have any performance issues. So it has to be something to do with the latest version of 
ImmediatelyFast.

MCC Island has a bunch of custom entities which is probably related to the issue I am having.

What might also be worth mentioning is I always have Vsync enabled (75 FPS, 75hz monitor). I will share my in-game options file, not sure if it will help out though.
[options.txt](https://github.com/RaphiMC/ImmediatelyFast/files/11215131/options.txt)

**Comment by RaphiMC** [comment] 2023-04-12 19:30
Do you get less FPS when uninstalling ImmediatelyFast as a whole and joining the same server compared to the latest version?

**Comment by BlizzLee** [comment] 2023-04-12 19:31
I'll test this out now real quick :)

**Comment by BlizzLee** [comment] 2023-04-12 19:39
So I do experience a little stuttering with the mod uninstalled, but it's not nearly as bad as my frame rate issues when i had the latest version installed. My frame rate without the mod sometimes drops to 73FPS which can cause minor stuttering, but with the latest version, my frame rate can go as low as 50.

(sorry, I'm trying not criticise your mod, the previous version of the mod helps a lot with stutter :D, it's just the latest version that hurts my performance on the server :( )

**Comment by RaphiMC** [comment] 2023-04-12 19:41
Can you install the latest version again and set debug_only_and_not_recommended_disable_mod_conflict_handling to true in the config file. Check if this resolves the issue

**Comment by BlizzLee** [comment] 2023-04-12 19:41
sure, one moment

**Comment by RaphiMC** [comment] 2023-04-12 19:43
Nvm that doesn't do what I wanted to test

**Comment by BlizzLee** [comment] 2023-04-12 19:44
Oh alrighty

**Comment by RaphiMC** [comment] 2023-04-12 19:45
Change it back to default and try this version instead: https://upload.raphimc.net/file/6V48SWldy7b3zOFU/EwV3RQG2I5ISHWtw/ImmediatelyFast-1.1.12.jar

**Comment by BlizzLee** [comment] 2023-04-12 19:45
Will do! 1 sec :)

**Comment by BlizzLee** [comment] 2023-04-12 19:48
I'm getting minor frame drops down to 73FPS, but it's waaay better. Almost no stuttering.

**Comment by BlizzLee** [comment] 2023-04-12 19:49
The small rate drop might just be to do with the server itself honestly because of the large amount of custom entities, should I try a vanilla SMP server perhaps?

**Comment by RaphiMC** [comment] 2023-04-12 19:50
So that FPS is within the range of deviation now to the old version. Its just weird that you report less FPS with the latest version than without the mod. Could you maybe retest that

**Comment by BlizzLee** [comment] 2023-04-12 19:52
Test again without the mod? Sure

**Comment by BlizzLee** [comment] 2023-04-12 19:59
So the lowest frame rate I saw was 68 without the mod, but it remained at 73 - 75fps most of the time, although I feel as if the stuttering was more frequent compared to using the mod file you sent me here

**Comment by RaphiMC** [comment] 2023-04-12 20:02
Ignore the test version I sent here for a moment and use the latest official version and check if thats worse than not having the mod. Make sure to test for a couple of minutes in roughly the same scenario

**Comment by BlizzLee** [comment] 2023-04-12 20:03
Alright, I'll test them for 5 min each

**Comment by RaphiMC** [comment] 2023-04-12 20:05
The problem on servers utilizing resource packs to modify the HUD is that they break in almost all cases with the optimizations the previous version of ImmediatelyFast had. In the latest version I auto disable optimizations which could lead to rendering errors on such servers which of course reduces the framerate compared to the old version. It should still be better than vanilla tho because I am not disabling everything, but only a couple of things which could break the rendering of the custom HUD stuff on mcc

**Comment by BlizzLee** [comment] 2023-04-12 20:10
I was thinking should I record what's happening and upload it to youtube for you to see?

**Comment by BlizzLee** [comment] 2023-04-12 20:10
I'll make 1 video with the mod, and another without it, 5 mins long for both

**Comment by RaphiMC** [comment] 2023-04-12 20:17
If you are certain to get less FPS with the latest version of the mod (The original one not the one I sent) than without it please install this mod: https://modrinth.com/mod/spark and run /sparkc profiler start --timeout 30 while standing still on the mcc server until it prints you the link. Do that twice, once without my mod and once with the latest version installed. Send both links here so I can take a closer look at the performance statistics. I will look at the videos as well. Thanks for cooperating

**Comment by BlizzLee** [comment] 2023-04-12 20:20
I'll install the Spark and set my recording quality to low just incase a high recording setting interferes with the test, but you'll be able to see the frame rate still.

Also I'm happy to cooperate. This mod has helped me a lot in the past and I want to continue using it :)

**Comment by RaphiMC** [comment] 2023-04-12 20:20
Don't record while doing the spark profiling. Stand still on the same spot in both test cases so the results are consistent

**Comment by BlizzLee** [comment] 2023-04-12 20:21
Will do!

**Comment by BlizzLee** [comment] 2023-04-12 20:30
With the mod installed - https://spark.lucko.me/F4ixFjjC2T
Without the mod installed - https://spark.lucko.me/RHBSRSHP8X

I actually noticed that if I stand completely still for longer than 10 seconds, my frame rate does recover a bit with the latest version of the mod installed. I'll do the recording now

**Comment by RaphiMC** [comment] 2023-04-12 20:34
So looking at the profiler results there is no apparent performance problem caused by ImmediatelyFast. The biggest performance "problem" I see is the fact that VSync is enabled. You could try disabling VSync and setting an FPS limit yourself. Set it to be around 10-20 above your actual monitors refresh rate

**Comment by RaphiMC** [comment] 2023-04-12 20:37
I will close the issue because the performance drop your experienced from switching to the latest version of ImmediatelyFast is intentional as it is necessary to fixe some rendering issues on servers with custom HUDs (The resource pack relies on the slow vanilla rendering. It also only disables parts of the optimization on such servers) which were reported with the old version. If you have further questions feel free to comment despite the issue being closed or join my discord for real time communication

**Closed as completed by RaphiMC** 2023-04-12 20:37 UTC
Labels: wontfix

**Comment by RaphiMC** [comment] 2023-04-12 20:41
I will add an option to disable that behaviour and restore the old behaviour at the cost of some rare rendering issues. It will be default disabled and you can enable it in the config when you upgrade again. In the mean time you can use the test version I uploaded which has that change implemented (It improves performance at the cost of rare render issues with HUD elements)
