### ISSUE TITLE
3D Items in Hotbar Greyed Out.

### ISSUE THREAD

**Issue by EliasRipley** [RaphiMC/ImmediatelyFast#211] opened 2024-05-06 11:45 UTC
As reported in Discord Server. (Same username - EliasRipley)
Found on MC 1.20.1 Forge (47.2.20) using latest version of IF.

3D Items are greyed out in the hotbar on our server.

Our modpack:
https://drive.google.com/drive/folders/0B31l3FNyi9gJeF9PWDJfNU1uVms?resourcekey=0-FuujApZ6mZbeI2_fHG1sFg&usp=drive_link

I suppose the ones that stand out that could cause something like this from my pack are:
Embeddium / Embeddium++
Radium (Server Side Only so not in pack.)
ModernFix
OutOfSight

This might be helpful to ya RK:
https://www.reddit.com/r/feedthebeast/comments/1aci7vj/what_mod_causes_hotbar_slots_to_be_grayed_out/
There's a user there who has also identified IF as the cause for the same issue.

EtherealGears, 3mo ago:
"I figured out what was doing this btw. It's a bug with ImmediatelyFast. It causes item textures that have 3D models to be grayed out in the HUD."

**Comment by EliasRipley** [comment] 2024-05-06 11:46
![2024-05-06_12 06 42](https://github.com/RaphiMC/ImmediatelyFast/assets/22055676/1932eeec-b91e-4aae-925f-fc57fa212fa2)
![2024-05-06_12 10 15](https://github.com/RaphiMC/ImmediatelyFast/assets/22055676/bbbf0c43-da38-453c-8255-2d8f5ff6019a)
![2024-05-06_12 12 06](https://github.com/RaphiMC/ImmediatelyFast/assets/22055676/86a8cfd9-e487-4638-ba40-d2e2dddb4514)
Screenshots displaying the issue / showing that it does not affect the inventory, only the hotbar.

**Comment by RaphiMC** [comment] 2024-05-29 22:36
Duplicate of #133

**Closed as completed by RaphiMC** 2024-05-29 22:36 UTC
Labels: bug, duplicate, confirmed, external-mod
