### ISSUE TITLE
Placed banners all appear completely white

### ISSUE THREAD

**Issue by YaCCBoy** [RaphiMC/ImmediatelyFast#10] opened 2022-12-14 18:38 UTC
As title says. All banners placed in a world appear completely white, no matter what patterns they had, or even if white wasn't their base color. The patterns do appear on the item, however.

https://user-images.githubusercontent.com/87284322/207682030-968e2048-239c-4227-9418-f43442100ea2.mp4

Mod version: 1.0.6
Minecraft version: 1.19.3
Fabric version: 0.14.11
Processor: Intel i5-1240P with integrated graphics

**Comment by RaphiMC** [comment] 2022-12-14 20:49
Could reproduce the bug. Seems like only 1.19.3 is affected and 1.19.2 is rendering the banners normally

**Comment by YaCCBoy** [comment] 2022-12-16 01:09
[UPDATE]
It seems the bug does not happen when banners are seen through colored glass. Possibly also applies to other transparent colored blocks like water. Does NOT apply with fully transparent blocks like regular glass.

https://user-images.githubusercontent.com/87284322/207999028-6d140fde-e0ee-4d07-8e0f-3d0604f3ef7b.mp4

**Comment by RaphiMC** [comment] 2022-12-16 06:33
I already found the cause of the issue: I was rendering the banner layers in the wrong order. I just have to test my fix a bit more to make sure nothing else broke from my changes and then I will release it

**Comment by RaphiMC** [comment] 2022-12-17 19:09
Should be fixed in ImmediatelyFast 1.0.7

**Closed by RaphiMC** 2022-12-17 19:09 UTC
