### ISSUE TITLE
Marium's Soulslike Weaponry mod causes hotbar item textures to not load properly

### ISSUE THREAD

**Issue by wool25** [RaphiMC/ImmediatelyFast#220] opened 2024-05-21 22:49 UTC
On fabric 1.20.1, using ImmediatelyFast 1.2.15 and Marium's SW 1.1.3, item textures in my hotbar would, whenever some 3D model items from that mod were either in my hotbar or my offhand in any slot (in the case below, the 7th slot);
- turn into colored squares the size of their sprite 
- vanish entirely
- have their texture replaced by a color of the item

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/108700081/440a789c-9202-4085-98d0-adf3449f8d30)
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/108700081/9f941a0d-00e6-439e-b99e-8c42ca53e2e0)
VS
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/108700081/b9048608-3fbd-473c-a0fd-d9e35c937fa1)

this is the latest.log file from loading the game to entering a world

[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/15396032/latest.log)

**Comment by Waoweens** [comment] 2024-05-26 04:57
i can reproduce this with guns from "Happiness (is a) Warm Gun" cybercat-mods/HWG#127

disabling `hud_batching` in the config seems to be a workaround for now if you don't want to disable the mod entirely

**Comment by RaphiMC** [comment] 2024-05-26 15:15
Fixed in latest dev build: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/9244167184

**Closed as completed by RaphiMC** 2024-05-26 15:15 UTC
Labels: bug, confirmed, external-mod
