### ISSUE TITLE
Player list renders weird on MCC Island

### ISSUE THREAD

**Issue by Kaizodude** [RaphiMC/ImmediatelyFast#35] opened 2023-01-28 23:39 UTC
When playing on the server play.mccisland.net with the newest version of ImmediatelyFast (1.1.8 for 1.19.2) the player list is bugged. 

This is what it looks like with ImmediatelyFast 1.1.8
![image](https://user-images.githubusercontent.com/2174905/215296006-993b192a-3c15-4819-8dbc-55960d70b12a.png)

This is what it looks like without ImmediatelyFast 1.1.8
![image](https://user-images.githubusercontent.com/2174905/215296051-a255d81c-c99f-4178-8611-f2a866263a72.png)

**Comment by Hyphrio** [comment] 2023-02-01 11:31
I could also replicate the same thing but it's worse if you're in a game as it creates white artifacts
![image](https://user-images.githubusercontent.com/79437385/216031153-91ceacf7-da37-42b9-91b5-fcc4b37ba8d2.png)
Downgrading to 1.0.x fixes the issue so it may be a regression.

**Comment by RaphiMC** [comment] 2023-02-01 15:03
The server is whitelisted and I can't test on it

**Comment by Kaizodude** [comment] 2023-02-02 02:41
Something similar happens on Tubnet, which is not whitelisted 
![image](https://user-images.githubusercontent.com/2174905/216217912-a5d1c4bc-6a50-4777-9e29-a71092a6faa9.png)

**Comment by Hyphrio** [comment] 2023-02-02 05:29
Hmm, seems like disabling HUD batching works around the issue
![image](https://user-images.githubusercontent.com/79437385/216239657-482483fd-14ad-4731-a628-90ca3a9fd771.png)

**Comment by RaphiMC** [comment] 2023-02-02 11:15
@Kaizodude I could not reproduce the issue. Do you have any other mods installed?

![image](https://user-images.githubusercontent.com/50594595/216310134-c63b0fa2-6709-4aa3-ad50-4f6463d762d5.png)

**Comment by RaphiMC** [comment] 2023-02-02 11:21
Nvm, I joined the server using my dev env (Which isn't logged in with a minecraft account and thus shows no skins in the player list). Could reproduce the issue in normal env

**Comment by Kaizodude** [comment] 2023-02-02 11:55
Being told by a friend the cause of this is due to this mod messing around with Minecrafts shaders as it also effects the sidebar having numbers on it, this server uses shaders to disable / hide those numbers
![image](https://user-images.githubusercontent.com/2174905/216318179-e5a51e1b-425b-42f3-a59e-4f802285333b.png)

**Comment by RaphiMC** [comment] 2023-02-02 11:58
IF is not messing with shaders, its the server that is messing with shaders and it seems to depend on the broken/slow vanilla rendering. If this is the case the only solution is to disable hud_batching in the config.
Could you send me the resource pack of that server (You should find it in %appdata%/.minecraft/server-resourcepacks)

**Comment by Hyphrio** [comment] 2023-02-02 12:04
I think the shader theory might have some weight into it as I tested if the issue is gone by disabling hud batching, which it did when I tested it.

**Comment by RaphiMC** [comment] 2023-02-02 12:06
Its most likely that. I have had issues with core shader modifications in the past. I made a feature request issue #37 which will temporarly auto disable IF features which are not compatible on the current server

**Comment by RaphiMC** [comment] 2023-03-28 20:11
Fixed in IF 1.1.12

**Closed as completed by RaphiMC** 2023-03-28 20:11 UTC
Labels: bug, confirmed
