### ISSUE TITLE
Support for vulkan mod

### ISSUE THREAD

**Issue by NinjaLegendmc** [RaphiMC/ImmediatelyFast#224] opened 2024-05-29 04:19 UTC
Please support to vulkan mod to use it!

**Comment by RaphiMC** [comment] 2024-05-29 05:45
Duplicate of #85

**Closed as completed by RaphiMC** 2024-05-29 05:45 UTC
Labels: duplicate

**Comment by NinjaLegendmc** [comment] 2024-06-05 11:01
> Duplicate of #85

Your 1.1.16 still support with vk I test it but It only available on 1.20.1
