### ISSUE TITLE
Compatibility: 1.20.[56]: Xaero Minimap shows a black rectangle instead of the map

### ISSUE THREAD

**Issue by MeeniMc** [RaphiMC/ImmediatelyFast#199] opened 2024-05-01 17:46 UTC
When using Xaero Minimap and Immediately Fast together, the minimap is broken: the minimap renders as a large black rectangle. Moving the minimap, the minimap frame moves and appears normal, but the black rectangle remains in the top left corner of the screen, and the minimap does not appear inside the frame. 

Behavior is normal in 1.20.4, and with only Xaero minimap

minecraft 1.20.6
immediatelyfast 1.2.12+1.20.5
xaerobetterpvp 24.1.3 (xaeroworldmap 1.38.6, but the world map works normally)

**Comment by RaphiMC** [comment] 2024-05-01 17:48
Most likely duplicate of #197

**Closed as completed by RaphiMC** 2024-05-01 17:48 UTC
Labels: duplicate
