### ISSUE TITLE
1.18.2 fabric version contains a trojan virus.

### ISSUE THREAD

**Issue by SDViolet** [RaphiMC/ImmediatelyFast#219] opened 2024-05-21 07:59 UTC
I downloaded the mod on a Fabric pack and launched it. Windows defender gave a warning and gave a trojan warning. I did 1 by 1 search and fount out, that it was this mod. 
<img width="356" alt="image" src="https://github.com/RaphiMC/ImmediatelyFast/assets/170406174/802c07b0-b9ec-4be5-a6a0-5d55493005ef"> (Details of Windows Defender)
It was the newest 1.18.2 Fabric version, please fix it.

**Comment by trnahuman** [comment] 2024-05-21 09:09
False report

**Comment by RaphiMC** [comment] 2024-05-21 09:54
This is a false positive and can be ignored.
Duplicate of https://github.com/RaphiMC/ImmediatelyFast/issues/142

**Closed as completed by RaphiMC** 2024-05-21 09:54 UTC
Labels: duplicate
