### ISSUE TITLE
Minecraft crashed!

### ISSUE THREAD

**Issue by tunaflsh** [RaphiMC/ImmediatelyFast#5] opened 2022-11-14 12:42 UTC
I've built a small piston contraption and by activating it Minecraft crashed with potential causes coming from More Culling, Indium and Sodium. However after disabling your mod, it didn't crash and by enabling the mod again I could reproduce the crash. I'm not sure if it's really related to your mod, because after some further testing I could not reproduce the crash anymore.

Log file: https://mclo.gs/2UTSIg1

**Comment by RaphiMC** [comment] 2022-11-14 13:01
Weird crash. Seems like some mod caused the block occlusion/culling cache to become inconsistent/broken. ImmediatelyFast does not touch that area and is thus most likely not the cause of that crash. I will close the issue for now. If it crashes again, try to find a minimal test setup to reproduce it and open a new issue

**Closed by RaphiMC** 2022-11-14 13:01 UTC
