### ISSUE TITLE
AppleSkin saturation is broken when installed with this mod & Armor Points ++

### ISSUE THREAD

**Issue by jmadarg** [RaphiMC/ImmediatelyFast#22] opened 2023-01-07 04:58 UTC
After updating ImmediatlyFast to 1.1.6 the saturation overlay added by AppleSkin stops working.

On 1.1.5:

![image](https://user-images.githubusercontent.com/62086445/211131812-ff3844ce-716a-4553-b724-304bf24450e6.png)

On 1.1.6:

![image](https://user-images.githubusercontent.com/62086445/211131851-d98bbad7-8e71-4b0e-a15f-1deefc71e3fa.png)

**Comment by MCSmallCai** [comment] 2023-01-07 06:50
I haven't seen this happen

**Comment by RaphiMC** [comment] 2023-01-07 09:43
Can you please send your list of installed mods and what minecraft version you are using. I can not reproduce that error when using the latest ImmediatelyFast and the latest AppleSkin version.

**Comment by jmadarg** [comment] 2023-01-07 10:13
Sure! As I seems to be the only one with the problem, I'm gonna try to pinpoint what else could be interacting.
This is the list of loaded mods according to my logs, lmk if you prefer a screenshot of the folder or if this is ok!

	- advancementinfo 1.19.1-fabric0.58.5-1.3.1
	- advancementplaques 1.4.6
	- advdebug 2.3.0
	- amecsapi 1.3.6+mc22w17a via mousewheelie
	- animatica 0.5+1.19
	- antighost 1.19.1-fabric0.58.5-1.1.5
	- appleskin 2.4.1+mc1.19
	- architectury 6.4.62
	- armorpointspp 3.0.5
	- auto_third_person 1.2.1
	- betteranimationscollection 4.0.5
	- betterbeds 1.2.0
	- betterf3 4.0.0
	- betterfpsdist 1.19.1-2.0
	- bettermounthud 1.2.0
	- bookshelf 16.2.16
	- borderlessmining 1.1.5+1.19
	- cachemyenderchest 1.0.2
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- cardinal-components-base 5.0.2 via puzzleslib
	- cardinal-components-block 5.0.2 via puzzleslib
	- cardinal-components-chunk 5.0.2 via puzzleslib
	- cardinal-components-entity 5.0.2 via puzzleslib
	- cardinal-components-world 5.0.2 via puzzleslib
	- cem 0.7.1
	- chat-up 2.1
	- chat_heads 0.9.0
	- chunksfadein 3.0.5-1.19
	- citresewn 1.1.2+1.19.2
	- citresewn-defaults 1.1.2+1.19.2 via citresewn
	- clickadv 3.0
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- coat 1.0.0-beta.19+mc22w17a via mousewheelie
	- collective-fabric 5.22
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_github_llamalad7_mixinextras 0.1.1 via immediatelyfast
	- com_github_luben_zstd-jni 1.5.2-2 via dashloader
	- com_github_pircbotx_pircbotx 12f5639c5d via twitchchat
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_moandjiezana_toml_toml4j 0.7.2 via chunksfadein
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- completeconfig-base 2.0.0-beta.3 via cem
	- completeconfig-gui-cloth 2.0.0-beta.3 via cem
	- conditional-mixin 0.3.0 via moreculling
	- configured 2.0.0
	- connectivity 1.19.2-3.7
	- continuity 2.0.1+1.19
	- controlling 10.0+7
	- creativecore 2.9.3
	- crowdin-translate 1.4+1.19 via antighost
	- dashloader 4.1.3+1.19
	- dcch 1.2
	- debugify 2.8.0
	- dev_isxander_settxi_settxi-core 2.10.5 via zoomify
	- dev_isxander_settxi_settxi-gui 2.10.5 via zoomify
	- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.5 via zoomify
	- dev_quantumfusion_hyphen 0.2.2 via dashloader
	- dev_quantumfusion_taski 1.1.0 via dashloader
	- draggable-resource-packs 3.0.1+build.9
	- eatinganimationid 1.9
	- enchantedtooltips 1.3.7-1.19
	- entity_texture_features 4.3.1
	- entityculling 1.5.2-mc1.19
	- error_notifier 1.0.9 via roughlyenoughitems
	- fabric-api 0.72.0+1.19.2
	- fabric-api-base 0.4.14+6e0787e690 via fabric-api
	- fabric-api-lookup-api-v1 1.6.13+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.1.0+82db024a90 via fabric-api
	- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.23+c6af733c90 via fabric-api
	- fabric-client-tags-api-v1 1.0.4+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.15+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.2.0+413cbbc790 via fabric-api
	- fabric-commands-v0 0.2.32+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.40+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.5.0+7c6cd14d90 via fabric-api
	- fabric-convention-tags-v1 1.2.1+27265b3490 via fabric-api
	- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.3.6+413cbbc790 via fabric-api
	- fabric-dimensions-v1 2.1.34+0d0f210290 via fabric-api
	- fabric-entity-events-v1 1.5.3+9244241690 via fabric-api
	- fabric-events-interaction-v0 0.4.33+562bff6e90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.33+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
	- fabric-item-api-v1 1.6.3+9785ec3590 via fabric-api
	- fabric-item-groups-v0 0.3.37+9244241690 via fabric-api
	- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via fabric-api
	- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
	- fabric-language-kotlin 1.9.0+kotlin.1.8.0
	- fabric-lifecycle-events-v1 2.2.3+1b46dc7890 via fabric-api
	- fabric-loot-api-v2 1.1.11+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.14+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.6+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.22+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.20+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.10+10eb22f490 via fabric-api
	- fabric-networking-v0 0.3.27+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.1.5+9785ec3590 via fabric-api
	- fabric-particles-v1 1.0.13+4d0d570390 via fabric-api
	- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
	- fabric-recipe-api-v1 1.0.0+413cbbc790 via fabric-api
	- fabric-registry-sync-v0 0.9.31+9244241690 via fabric-api
	- fabric-renderer-api-v1 1.2.0+2e5408b590 via fabric-api
	- fabric-renderer-indigo 0.7.0+2e5408b590 via fabric-api
	- fabric-renderer-registries-v1 3.2.23+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.18+6e0787e690 via fabric-api
	- fabric-rendering-fluids-v1 3.0.10+4d0d570390 via fabric-api
	- fabric-rendering-v0 1.1.26+df3654b390 via fabric-api
	- fabric-rendering-v1 1.12.0+08b73de490 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.8.3+251d254a90 via fabric-api
	- fabric-screen-api-v1 1.0.31+4d0d570390 via fabric-api
	- fabric-screen-handler-api-v1 1.3.6+1cc24b1b90 via fabric-api
	- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
	- fabric-textures-v0 1.0.23+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.5+413cbbc790 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
	- fabricloader 0.14.11
	- fabricskyboxes 0.6.1+mc1.19.2
	- fastload 2.6.10
	- ferritecore 5.0.3
	- fiber 0.23.0-2 via armorpointspp
	- forgeconfigapiport 4.2.9
	- freecam 1.1.6
	- fsb-interop 1.1.3+mc1.19.2-build.25
	- gammautils 1.6.10
	- held-item-info 1.4.0
	- here-be-no-dragons 1.0.0
	- iceberg 1.0.46
	- immediatelyfast 1.1.6
	- indium 1.0.9+mc1.19.2
	- inventoryhud 3.4.7
	- io_github_douira_glsl-transformer 2.0.0-pre8 via iris
	- iris 1.5.0
	- itemphysiclite 1.5.1
	- jade 8.6.4
	- jadeaddons 3.0.0
	- java 18
	- kirin 1.11.1 via presencefootsteps
	- krypton 0.2.1
	- kyrptconfig 1.4.14-1.19 via enchantedtooltips
	- lambdabettergrass 1.3.0+1.19
	- lambdynlights 2.2.0+1.19.2
	- lazy-language-loader 0.3.1
	- lazydfu 0.1.3
	- legendarytooltips 1.3.3
	- lightoverlay 7.0.0
	- limitedchunks 1.19.2-2.6
	- lithium 0.10.4
	- memoryleakfix 1.19.3-0.7.0
	- midnightlib 1.0.0
	- minecraft 1.19.2
	- mixintrace 1.1.1+1.17
	- modmenu 4.1.2
	- morechathistory 1.1.1
	- moreculling 1.19.1-0.13.0
	- mousetweaks 2.22
	- mousewheelie 1.10.6+mc1.19.2
	- nameplate 1.0.10
	- nbttooltips 0.1.2-1.19
	- no-resource-pack-warnings 1.0.0
	- nochatreports 1.19.2-v1.13.12
	- notenoughanimations 1.6.2
	- optigui 1.1.6
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.11.1 via iris
	- org_apache_commons_commons-text 1.9 via optigui
	- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
	- org_javassist_javassist 3.28.0-GA via yungsapi
	- org_jetbrains_kotlin_kotlin-reflect 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_reflections_reflections 0.10.2 via yungsapi
	- paxi 1.19.2-Fabric-3.0
	- presencefootsteps 1.6.4
	- pride 1.1.2+1.19 via lambdynlights
	- prism 1.0.3
	- puzzle 1.4.2-1.19
	- puzzle-base 1.4.2-1.19 via puzzle
	- puzzle-gui 1.4.2-1.19 via puzzle
	- puzzle-models 1.4.2-1.19 via puzzle
	- puzzle-splashscreen 1.4.2-1.19 via puzzle
	- puzzleslib 4.3.12
	- reacharound 1.1.1
	- rebind_narrator 2.0.0
	- reeses-sodium-options 1.4.9+mc1.19.2-build.67
	- roughly_enough_loot_tables 1.19-1.0
	- roughly_enough_trades 1.19-1.0
	- roughlyenoughitems 9.1.580
	- roughlyenoughprofessions 1.1.3
	- roughlyenoughresources 2.6.0
	- sdrp 3.0.4-build.27+mc1.19.2
	- seethroughlava 3.0.1-1.19
	- settxi-gui-yacl 2.10.5 via zoomify
	- shulkerboxtooltip 3.2.2+1.19.2
	- skinlayers 1.5.2-mc1.19.1
	- smoothboot 1.19-1.7.1
	- smoothchunk 1.19.1-2.0
	- sodium 0.4.4+build.18
	- sodium-extra 0.4.16+mc1.19.2-build.90
	- sound_physics_remastered 1.19.2-1.0.18
	- spark 1.10.17
	- spruceui 4.1.0+1.19.2 via lambdynlights
	- starlight 1.1.1+fabric.ae22326
	- status-effect-bars 1.0.1
	- third_person_maps 1.4.0
	- toolstats 12.0.2
	- tweed4_annotated 1.3.1+mc22w17a via mousewheelie
	- tweed4_base 1.7.1+mc22w17a via mousewheelie
	- tweed4_data 1.2.1+mc22w17a via mousewheelie
	- tweed4_data_hjson 1.1.1+mc22w17a via mousewheelie
	- tweed4_tailor_coat 1.1.3+mc22w17a via mousewheelie
	- tweed4_tailor_screen 1.1.3+mc22w17a via mousewheelie
	- twitchchat 0.14.0b
	- vt_downloader 2.0.0
	- xaerominimap 22.17.0
	- xaeroworldmap 1.28.7
	- yet-another-config-lib 1.7.1
	- yungsapi 1.19.2-Fabric-3.8.2
	- zoomify 2.9.0

**Comment by RaphiMC** [comment] 2023-01-07 10:15
Thats a lot of mods. Would appreciate you doing the pinpointing

**Comment by jmadarg** [comment] 2023-01-07 10:17
Ok! Working on it, and sorry, I forgot to mention the version, I'm playing 1.19.2 Fabric

**Comment by jmadarg** [comment] 2023-01-07 10:57
Found it! Removing [Armor Points ++](https://www.curseforge.com/minecraft/mc-mods/armorpoints) solves the problem

**Comment by StockiesLad** [comment] 2023-01-07 10:58
Please rename it to "AppleSkin saturation is broken when installed with this mod & Armor Points ++"

**Comment by StockiesLad** [comment] 2023-01-07 10:59
As a mod dev, good titles really help. I think RK will appreciate it.

**Comment by RaphiMC** [comment] 2023-01-07 11:08
I can not reproduce the issue simply by installing Armor Points ++. Can you maybe send your configuration of that mod?

**Comment by StockiesLad** [comment] 2023-01-07 11:12
- optigui 1.1.6


sounds... dodgy

**Comment by jmadarg** [comment] 2023-01-07 11:39
Tried a fresh instance with only AppleSkin, Armor Points ++, ImmediatlyFast and the Fabric API using the default configs for everything and the problem persist. Here is the log in case it has some extra info that could help.

[2023-01-07-2.log](https://github.com/RaphiMC/ImmediatelyFast/files/10366127/2023-01-07-2.log)

And the file you asked for (I only disabled the texts), but as I said, it happens even with the default. (Had to change the extension to txt to upload it, but it should be a json)

[armorpointspp.txt](https://github.com/RaphiMC/ImmediatelyFast/files/10366129/armorpointspp.txt)

**Comment by Hyomoto** [comment] 2023-01-12 21:23
I will also confirm I came here *specifically* to see if this bug was happening.  Downpatching to 1.1.5 also fixed this issue, it's something I would guess with the z sorting changes.  At least, that was the logic I used when trying to figure out which mod I updated that suddenly caused the saturation bar to go walkabout.

I see this bug with 1.1.6 ImmediatelyFast, Armorpoints++ 3.0.5, and Appleskin 2.4.1 all for 1.19.2 and fabric 0.14.12 + 0.72.0 api.

To be very clear, the saturation layer does not appear.  All other Appleskin features seem to work fine.

**Comment by RaphiMC** [comment] 2023-01-12 21:24
What mods did you use. I could not reproduce the issue with IF, AppleSkin and Armor Points ++ alone. Do I need to change something in the configuration? Also what minecraft version did you test it on?

**Comment by Hyomoto** [comment] 2023-01-13 01:10
As included above, MC is 1.19.2 with fabric loader 0.14.12 and the fabric API 0.72.0.  Settings are default.  If you aren't seeing anything with those, as described, then there must be another culprit.  I'm also using pretty much all of the optimization mods for fabric, most relevant being OptiGUI, Exordium and perhaps Iris.

**Comment by RaphiMC** [comment] 2023-01-13 10:00
Can you maybe try removing mods until you find the culprit. Its easier for you to do that than for me to download a lot of mods

**Comment by Hyomoto** [comment] 2023-01-16 15:08
It is easier for me to do the work, yeah.  So I did.  ImmediatelyFast 1.1.6 is the culprit.  First, I removed all my mods.  Then, made filled the folder with only the for-test mods: fabric, immediately fast, appleskin and armorpoints.
![image](https://user-images.githubusercontent.com/6281477/212708791-124dad66-7f91-41d7-9ae8-92f3b3ae9f9a.png)
And voila, no saturation bar:
![image](https://user-images.githubusercontent.com/6281477/212708912-8666a514-3eef-4956-aadb-246001228a22.png)

Next up, remove ImmediatelyFast 1.1.6 and replace it with 1.1.5:
![image](https://user-images.githubusercontent.com/6281477/212709071-5acaa702-7bba-4f29-81ba-6c19633cc009.png)
And voila, saturation reappears:
![image](https://user-images.githubusercontent.com/6281477/212709216-cca3075b-c49b-4de7-8698-8f58f07d0278.png)

Bit of an anti-climax, really.  I had put aside time thinking I'd have to find some obscure incompatibility but it does at least verify, yes: these mods cause this issue.  It's worth noting, yes, you can also fix the Appleskin display issue by getting rid of Armorpoints.  That mod has some "compatibility" with Appleskin and it's *that* I would guess is the source vector? My guess is that Armorpoints does something to support Appleskin that IF interferes with.  Here's the commit for "appleskin support" in AP++
<https://github.com/Cheos137/ArmorpointsPlusplus/commit/83ed8d6b6bc1cb5f3eabbf1ab38285612925962d>
Also, they seem to be working on a new version but last official version was July of last year, so it could be it has actually been fixed whatever the problem may be but perhaps their code will provide the needed clue.

For *absolute* completeness on this subject, MC and fabric loader version:
![image](https://user-images.githubusercontent.com/6281477/212709516-bb14eb83-1c25-4e8c-a15a-6b862ee5e340.png)

**Comment by RaphiMC** [comment] 2023-01-16 15:10
Thanks for your extensive testing. I will look into the issue in the next days

**Comment by jmadarg** [comment] 2023-01-19 01:02
Found a fix! By disabling exhaustion underlay (everything else on their defaults), the saturation overlay comes back.

![image](https://user-images.githubusercontent.com/62086445/213330753-74a8eabd-9cf5-46bb-97e1-43845359cbf2.png)

![image](https://user-images.githubusercontent.com/62086445/213331216-9ef9fe4f-d605-41a7-a116-0374fefba5ac.png)

Should I close the issue?

**Comment by StockiesLad** [comment] 2023-01-19 05:00
No, because, you have to disable a feature to get it to work properly.

**Comment by RaphiMC** [comment] 2023-01-19 11:53
Can you verify if the issue still occurs with IF 1.1.7
[ImmediatelyFast-1.1.7.zip](https://github.com/RaphiMC/ImmediatelyFast/files/10456438/ImmediatelyFast-1.1.7.zip)

**Comment by jmadarg** [comment] 2023-01-19 11:56
I tested earlier by building it (and that was when I thought of changing the settings), but didn't change anything, gonna give it another try with that file

**Comment by jmadarg** [comment] 2023-01-19 12:06
The issue still occurs with IF 1.1.7, also tried updating the instance to 1.19.3, but no luck

**Comment by Hyomoto** [comment] 2023-01-20 07:10
I can also confirm the issue persists in 1.1.7

**Comment by RaphiMC** [comment] 2023-01-22 20:13
Could not reproduce with those mods (And IF 1.1.7) using their default config.
![image](https://user-images.githubusercontent.com/50594595/213938012-b0899a6f-9bef-41fc-b264-5cde0bb85745.png)

**Comment by RaphiMC** [comment] 2023-04-29 11:20
The issue should be fixed. Someone please verify before I close it: https://upload.raphimc.net/file/K79pUE69C39gtbJI/0zU93mVaNIWh48GR/ImmediatelyFast-1.1.13%2B1.19.4.jar

**Comment by RaphiMC** [comment] 2023-05-18 20:12
Closed due to inactivity

**Closed as completed by RaphiMC** 2023-05-18 20:12 UTC
Labels: bug, confirmed, external-mod
