### ISSUE TITLE
Black text with Wynntils

### ISSUE THREAD

**Issue by cadenkriese** [RaphiMC/ImmediatelyFast#50] opened 2023-03-25 10:45 UTC
When using [Wynntils](https://github.com/Wynntils/Artemis), some of the text Wynntils renders appears black. As well as the vanilla item count number. This was extremely finicky to reproduce and required multiple relogs / reboots sometimes but I'm fairly certain the incompatibility is between only IF and Wynntils.

![image](https://user-images.githubusercontent.com/13630061/227712453-03a44bc4-9e05-4050-b69d-1b6d5fb66075.png)

**Comment by Frontear** [comment] 2023-04-26 04:56
Furthermore, when using the Shaman, using Aura will break HUD rendering.

**Comment by nl32** [comment] 2023-05-02 02:38
This issue also occurs with Iris 1.6.2 when using a shader pack.

**Comment by RaphiMC** [comment] 2023-05-02 05:42
Please open a seperate issue for the Iris issue

**Comment by RaphiMC** [comment] 2023-07-08 12:13
Can you check if this build fixes the issue: https://upload.raphimc.net/file/zX9rmo122VwZxRiz/z4SkCl4Fq9xFIZu6/ImmediatelyFast-1.1.16-SNAPSHOT%2B1.20.1.jar

**Comment by cadenkriese** [comment] 2023-07-09 07:34
Is that build the same as the 1.1.16 release? Wynntils isn't updated to 1.20.1 yet, so I used the 1.19.4 jar, and I can't recreate the issue yet. I'll try more testing on my main setup tomorrow.

Thank you for digging into this! I don't imagine it'd be straightforward to understand and patch.

**Comment by RaphiMC** [comment] 2023-07-09 09:39
Yes its the same build. I released it yesterday because the new patch seemed to work pretty well. Close the issue yourself when you tested it and confirmed its fixed

**Closed as completed** 2023-07-09 19:12 UTC
Labels: bug
