### ISSUE TITLE
[macOS only] Faster without the ImmediatelyFast mod

### ISSUE THREAD

**Issue by mrjasonn** [RaphiMC/ImmediatelyFast#279] opened 2024-10-24 09:29 UTC
I am on a Mac on Minecraft 1.21.3 and there seems to be a performance regression with this mod. I have checked the logs and there seems to be no relevant log information. I am also using Sodium, Iris and Gamma Utils alongside this mod. This seems to be more of an issue when there are more entities like name tags on servers like Hypixel. I feel like it is name tags that mainly cause the issue. ImmediatelyFast version: 1.3.0

**Comment by RaphiMC** [comment] 2024-10-24 09:44
Upload the game log. Upload a spark profile result (with and without IF (no other mods except for sodium)) and FPS numbers you got during that test. Ensure you test the same scene.

**Comment by mrjasonn** [comment] 2024-10-24 10:07
> Upload the game log. Upload a spark profile result (with and without IF (no other mods except for sodium)) and FPS numbers you got during that test. Ensure you test the same scene.

Here it is:
With IF: [https://mclo.gs/vU1Twxh](https://mclo.gs/vU1Twxh) and [https://spark.lucko.me/v1fzKxVqU3](https://spark.lucko.me/v1fzKxVqU3)
![2024-10-24_18 29 38](https://github.com/user-attachments/assets/5b6b6a36-47e4-4902-b574-59dd51184963)
Without IF: [https://mclo.gs/ZTHO5Hs](https://mclo.gs/ZTHO5Hs) and [https://spark.lucko.me/x70UAXUjc4](https://spark.lucko.me/x70UAXUjc4)
![2024-10-24_18 31 00](https://github.com/user-attachments/assets/e1881554-1447-4ba8-a886-ff296caf6a3a)

I have included Fabric API because spark needs it and kept it included in both tests for consistency.

**Comment by RaphiMC** [comment] 2024-10-24 10:12
Both tests show the same FPS. Can you retest with VSYNC disabled. No log needed anymore, just spark result and FPS numbers

**Comment by mrjasonn** [comment] 2024-10-24 10:34
> Both tests show the same FPS. Can you retest with VSYNC disabled. No log needed anymore, just spark result and FPS numbers

Ok, I have updated the screenshots. Even though they are a little bit different, they should be close enough. I have also tested this in an empty lobby this time around.

**Comment by RaphiMC** [comment] 2024-10-24 11:51
Please update the spark profile results as well

**Comment by mrjasonn** [comment] 2024-10-24 14:15
> Please update the spark profile results as well

Hi, sorry for the response that is a little late, but it has been updated now.

**Comment by RaphiMC** [comment] 2024-10-24 14:20
Try disabling the fast buffer upload optimization in the config and compare the FPS again

**Comment by mrjasonn** [comment] 2024-10-24 14:42
> Try disabling the fast buffer upload optimization in the config and compare the FPS again

Isn't that optimization disabled for Macs already due to unsupported OpenGL or something? Or is it supposed to but it's somehow not?

**Comment by RaphiMC** [comment] 2024-10-24 14:44
I enabled it for macs in 1.21.3 due to the different technique used to implement fast buffer upload. I hoped it would work on macs, but apparently not. But test it to confirm if its really that. If it is I will disable it on macs again

**Comment by mrjasonn** [comment] 2024-10-24 15:33
> I enabled it for macs in 1.21.3 due to the different technique used to implement fast buffer upload. I hoped it would work on macs, but apparently not. But test it to confirm if its really that. If it is I will disable it on macs again

It seems to really be the problem with the fast buffer upload optimization after testing

**Comment by RaphiMC** [comment] 2024-10-24 15:37
> It seems to really be the problem with the fast buffer upload optimization after testing

Upload new FPS tests (with fast buffer upload disabled. one with IF and one without IF) and their according spark profile (new post, not edit the previous one)

**Comment by mrjasonn** [comment] 2024-10-25 00:02
> > It seems to really be the problem with the fast buffer upload optimization after testing
> 
> Upload new FPS tests (with fast buffer upload disabled. one with IF and one without IF) and their according spark profile (new post, not edit the previous one)

@RaphiMC Here is the new updated comparison:
With IF (fast buffer upload disabled): [https://spark.lucko.me/4l2jeKPopg](https://spark.lucko.me/4l2jeKPopg)
![2024-10-25_07 59 32](https://github.com/user-attachments/assets/dd8498bf-fd92-470c-9d8d-826c7c200a15)
Without IF: [https://spark.lucko.me/buucRnVdaL](https://spark.lucko.me/buucRnVdaL)
![2024-10-25_07 57 52](https://github.com/user-attachments/assets/67a07538-f3f1-4fb4-a386-054067d9e44a)

**Comment by RaphiMC** [comment] 2024-10-25 10:43
ImmediatelyFast should now auto disable the fast buffer upload optimization if the mod is ran on Apple GPUs. To test it delete the config file (or reenable the fast buffer upload optimization) and install this version: https://upload.raphimc.net/file/SIzBMHWlbFiQi552/4He5jklatdhOs5lD/ImmediatelyFast-Fabric-1.3.1-SNAPSHOT%2B1.21.3.jar

Check the FPS and upload the game log so I can confirm that its fixed now

**Comment by mrjasonn** [comment] 2024-10-25 13:56
> ImmediatelyFast should now auto disable the fast buffer upload optimization if the mod is ran on Apple GPUs. To test it delete the config file (or reenable the fast buffer upload optimization) and install this version: https://upload.raphimc.net/file/SIzBMHWlbFiQi552/4He5jklatdhOs5lD/ImmediatelyFast-Fabric-1.3.1-SNAPSHOT%2B1.21.3.jar
> 
> Check the FPS and upload the game log so I can confirm that its fixed now

@RaphiMC The FPS has improved after your patch. Thanks. Here is the game log, the logspam is a Hypixel issue, but do indeed check if IF does something unexpected in the log. Here is the log: [https://mclo.gs/ENXUDvu](https://mclo.gs/ENXUDvu).
The patch also seems to work well with my other mods that I use, which is nice.

**Closed as completed** 2024-10-25 14:09 UTC
Labels: bug
