### ISSUE TITLE
Crash on Feather Client

### ISSUE THREAD

**Issue by kispintyi** [RaphiMC/ImmediatelyFast#78] opened 2023-06-26 20:04 UTC
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of me.replet.client.Mixins.ButtonWidgetAccessor failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)
Caused by: java.lang.RuntimeException: Mixin transformation of me.replet.client.Mixins.ButtonWidgetAccessor failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at me.replet.client.crashui.GuiProblemScreen.method_25426(GuiProblemScreen.java:29)
	at net.minecraft.class_437.method_25423(class_437.java:297)
	at net.minecraft.class_310.method_1507(class_310.java:1080)
	at net.minecraft.class_310.method_1565(class_310.java:21112)
	at net.minecraft.client.main.Main.main(Main.java:221)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for me.replet.client.Mixins.ButtonWidgetAccessor. Mixin is defined in vanillafix.crashui.mixins.json and cannot be referenced directly
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 17 more

**Comment by kispintyi** [comment] 2023-06-26 20:05
at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

**Comment by RaphiMC** [comment] 2023-06-26 20:05
Duplicate of #75

**Closed as completed by RaphiMC** 2023-06-26 20:05 UTC
Labels: invalid
